"""
Ontology generation service
interface1:Analyze text content,Generate entity and relationship type definitions suitable for social simulation
"""

import json
from typing import Dict, Any, List, Optional
from ..utils.llm_client import LLMClient


# System prompt words generated by ontology
ONTOLOGY_SYSTEM_PROMPT = """You are a professional knowledge graph ontology design expert.Your task is to analyze the given text content and simulate the requirements,Designed to fit**Social media public opinion simulation**Entity types and relationship types.

**important:You must output a validJSONformat data,Do not output anything else.**

## Core mission background

we are building a**Social media public opinion simulation system**.in this system:
- Every entity has a voice on social media,interactive,disseminating information"account"or"main body"
- Entities affect each other,Forward,Comment,respond
- We need to simulate the reactions of all parties and information dissemination paths in public opinion events

therefore,**The entity must be real in reality,Subjects who can speak out and interact on social media**:

**can be**:
- specific individuals(public figure,party,opinion leader,Experts and scholars,ordinary people)
- company,enterprise(Including its official account)
- Organizational structure(University,association,NGO,Trade unions, etc.)
- government departments,regulatory agency
- media organization(newspaper,TV station,self media,website)
- The social media platform itself
- representatives of specific groups(such as alumni association,fan club,rights protection groups, etc.)

**cannot be**:
- abstraction(like"public opinion","mood","trend")
- theme/topic(like"academic integrity","education reform")
- point of view/manner(like"Supporters","Opposition")

## Output format

Please outputJSONFormat,Contains the following structure:

```json
{
    "entity_types": [
        {
            "name": "Entity type name(English,PascalCase)",
            "description": "short description(English,no more than100character)",
            "attributes": [
                {
                    "name": "attribute name(English,snake_case)",
                    "type": "text",
                    "description": "Property description"
                }
            ],
            "examples": ["Example entity1", "Example entity2"]
        }
    ],
    "edge_types": [
        {
            "name": "Relationship type name(English,UPPER_SNAKE_CASE)",
            "description": "short description(English,no more than100character)",
            "source_targets": [
                {"source": "Source entity type", "target": "target entity type"}
            ],
            "attributes": []
        }
    ],
    "analysis_summary": "A brief analysis of the content of the text"
}
```

## Design Guidelines(extremely important!)

### 1. Entity type design - must be strictly followed

**Quantity requirements:Must be just right10entity type**

**Hierarchy requirements(Must contain both concrete type and cover type)**:

your10Entity types must contain the following levels:

A. **Cover types (required, placed at end of list, 2 items)**:
   - `Person`: Any type of cover-up for an individual natural person.When a person does not fit into other more specific person types,fall into this category.
   - `Organization`: Types of cover for any organization.When an organization does not belong to another more specific organization type,fall into this category.

B. **Concrete types (8 items, designed based on text content)**:
   - Target the main characters that appear in the text,Design more specific types
   - For example:If the text relates to an academic event,can have `Student`, `Professor`, `University`
   - For example:If the text relates to a business event,can have `Company`, `CEO`, `Employee`

**Why do you need a cover-up type?**:
- Various characters will appear in the text,like"Primary and secondary school teachers","Passerby","A certain netizen"
- If there is no specific type match,they should be classified `Person`
- Same reason,small organization,Temporary groups, etc. should be classified under `Organization`

**Type-specific design principles**:
- Identify frequently occurring or key character types from text
- Each concrete type should have clear boundaries,avoid overlap
- description The difference between this type and the cover-up type must be clearly stated

### 2. Relationship type design

- quantity: 6-10
- Relationships should reflect real connections in social media interactions
- ensure relationship source_targets Covers the entity types you define

### 3. attribute design

- each entity type1-3key attributes
- **Notice**:Property name cannot be used `name`,`uuid`,`group_id`,`created_at`,`summary`(These are system reserved words)
- Recommended:`full_name`, `title`, `role`, `position`, `location`, `description` wait

## Entity type reference

**personal category(specific)**:
- Student: student
- Professor: professor/scholar
- Journalist: reporter
- Celebrity: star/internet celebrity
- Executive: executive
- Official: government officials
- Lawyer: lawyer
- Doctor: doctor

**personal category(reveal all the details)**:
- Person: any natural person(Used when it does not belong to the above specific types)

**Organization type(specific)**:
- University: College
- Company: company enterprise
- GovernmentAgency: government agency
- MediaOutlet: media organization
- Hospital: Hospital
- School: Primary and secondary schools
- NGO: non-governmental organization

**Organization type(reveal all the details)**:
- Organization: any organization(Used when it does not belong to the above specific types)

## Relationship type reference

- WORKS_FOR: working on
- STUDIES_AT: Studied at
- AFFILIATED_WITH: Belong to
- REPRESENTS: represent
- REGULATES: supervision
- REPORTS_ON: report
- COMMENTS_ON: Comment
- RESPONDS_TO: respond
- SUPPORTS: support
- OPPOSES: be opposed to
- COLLABORATES_WITH: cooperate
- COMPETES_WITH: compete
"""


class OntologyGenerator:
    """
    ontology generator
    Analyze text content,Generate entity and relationship type definitions
    """
    
    def __init__(self, llm_client: Optional[LLMClient] = None):
        self.llm_client = llm_client or LLMClient()
    
    def generate(
        self,
        document_texts: List[str],
        simulation_requirement: str,
        additional_context: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generate ontology definition
        
        Args:
            document_texts: Document text list
            simulation_requirement: Simulation requirement description
            additional_context: extra context
            
        Returns:
            ontology definition(entity_types, edge_typeswait)
        """
        # Build user messages
        user_message = self._build_user_message(
            document_texts, 
            simulation_requirement,
            additional_context
        )
        
        messages = [
            {"role": "system", "content": ONTOLOGY_SYSTEM_PROMPT},
            {"role": "user", "content": user_message}
        ]
        
        # callLLM
        result = self.llm_client.chat_json(
            messages=messages,
            temperature=0.3,
            max_tokens=4096
        )
        
        # Validation and post-processing
        result = self._validate_and_process(result)
        
        return result
    
    # pass to LLM The maximum length of text(5Ten thousand words)
    MAX_TEXT_LENGTH_FOR_LLM = 50000
    
    def _build_user_message(
        self,
        document_texts: List[str],
        simulation_requirement: str,
        additional_context: Optional[str]
    ) -> str:
        """Build user messages"""
        
        # Merge text
        combined_text = "\n\n---\n\n".join(document_texts)
        original_length = len(combined_text)
        
        # If the text exceeds5Ten thousand words,Truncate(Only affects the transmissionLLMcontent,Does not affect map construction)
        if len(combined_text) > self.MAX_TEXT_LENGTH_FOR_LLM:
            combined_text = combined_text[:self.MAX_TEXT_LENGTH_FOR_LLM]
            combined_text += f"\n\n...(Total original text{original_length}Character,Before interception{self.MAX_TEXT_LENGTH_FOR_LLM}Words used for ontology analysis)..."
        
        message = f"""## Simulation requirements

{simulation_requirement}

## Document content

{combined_text}
"""
        
        if additional_context:
            message += f"""
## Additional instructions

{additional_context}
"""
        
        message += """
Please follow the above,Design entity types and relationship types suitable for social opinion simulation.

**rules that must be followed**:
1. Must be output exactly10entity type
2. at last2Must be a cover-up type:Person(Personal secret)and Organization(Organizations keep track of everything)
3. forward8A specific type designed based on text content
4. All entity types must be real-life subjects that can speak,It cannot be an abstract concept
5. Property name cannot be used name,uuid,group_id Wait for reserved words,use full_name,org_name Wait for replacement
"""
        
        return message
    
    def _validate_and_process(self, result: Dict[str, Any]) -> Dict[str, Any]:
        """Validation and post-processing results"""
        
        # Make sure required fields exist
        if "entity_types" not in result:
            result["entity_types"] = []
        if "edge_types" not in result:
            result["edge_types"] = []
        if "analysis_summary" not in result:
            result["analysis_summary"] = ""
        
        # Validate entity type
        for entity in result["entity_types"]:
            if "attributes" not in entity:
                entity["attributes"] = []
            if "examples" not in entity:
                entity["examples"] = []
            # make suredescriptionno more than100character
            if len(entity.get("description", "")) > 100:
                entity["description"] = entity["description"][:97] + "..."
        
        # Verify relationship type
        for edge in result["edge_types"]:
            if "source_targets" not in edge:
                edge["source_targets"] = []
            if "attributes" not in edge:
                edge["attributes"] = []
            if len(edge.get("description", "")) > 100:
                edge["description"] = edge["description"][:97] + "..."
        
        # Zep API limit:most 10 custom entity types,most 10 custom edge types
        MAX_ENTITY_TYPES = 10
        MAX_EDGE_TYPES = 10
        
        # Backpack type definition
        person_fallback = {
            "name": "Person",
            "description": "Any individual person not fitting other specific person types.",
            "attributes": [
                {"name": "full_name", "type": "text", "description": "Full name of the person"},
                {"name": "role", "type": "text", "description": "Role or occupation"}
            ],
            "examples": ["ordinary citizen", "anonymous netizen"]
        }
        
        organization_fallback = {
            "name": "Organization",
            "description": "Any organization not fitting other specific organization types.",
            "attributes": [
                {"name": "org_name", "type": "text", "description": "Name of the organization"},
                {"name": "org_type", "type": "text", "description": "Type of organization"}
            ],
            "examples": ["small business", "community group"]
        }
        
        # Check if there is already a pocket type
        entity_names = {e["name"] for e in result["entity_types"]}
        has_person = "Person" in entity_names
        has_organization = "Organization" in entity_names
        
        # The type of cover that needs to be added
        fallbacks_to_add = []
        if not has_person:
            fallbacks_to_add.append(person_fallback)
        if not has_organization:
            fallbacks_to_add.append(organization_fallback)
        
        if fallbacks_to_add:
            current_count = len(result["entity_types"])
            needed_slots = len(fallbacks_to_add)
            
            # If adding would exceed 10, some existing types need to be removed
            if current_count + needed_slots > MAX_ENTITY_TYPES:
                # Calculate how many need to be removed
                to_remove = current_count + needed_slots - MAX_ENTITY_TYPES
                # remove from end(Keep the more important concrete types from the front)
                result["entity_types"] = result["entity_types"][:-to_remove]
            
            # Add cover type
            result["entity_types"].extend(fallbacks_to_add)
        
        # Finally ensure that the limit is not exceeded(defensive programming)
        if len(result["entity_types"]) > MAX_ENTITY_TYPES:
            result["entity_types"] = result["entity_types"][:MAX_ENTITY_TYPES]
        
        if len(result["edge_types"]) > MAX_EDGE_TYPES:
            result["edge_types"] = result["edge_types"][:MAX_EDGE_TYPES]
        
        return result
    
    def generate_python_code(self, ontology: Dict[str, Any]) -> str:
        """
        Convert ontology definition toPythoncode(similarontology.py)
        
        Args:
            ontology: ontology definition
            
        Returns:
            Pythoncode string
        """
        code_lines = [
            '"""',
            'Custom entity type definition',
            'Depend onMiroFishAutomatically generated,Used for social public opinion simulation',
            '"""',
            '',
            'from pydantic import Field',
            'from zep_cloud.external_clients.ontology import EntityModel, EntityText, EdgeModel',
            '',
            '',
            '# ============== Entity type definition ==============',
            '',
        ]
        
        # Generate entity type
        for entity in ontology.get("entity_types", []):
            name = entity["name"]
            desc = entity.get("description", f"A {name} entity.")
            
            code_lines.append(f'class {name}(EntityModel):')
            code_lines.append(f'    """{desc}"""')
            
            attrs = entity.get("attributes", [])
            if attrs:
                for attr in attrs:
                    attr_name = attr["name"]
                    attr_desc = attr.get("description", attr_name)
                    code_lines.append(f'    {attr_name}: EntityText = Field(')
                    code_lines.append(f'        description="{attr_desc}",')
                    code_lines.append(f'        default=None')
                    code_lines.append(f'    )')
            else:
                code_lines.append('    pass')
            
            code_lines.append('')
            code_lines.append('')
        
        code_lines.append('# ============== Relationship type definition ==============')
        code_lines.append('')
        
        # Generate relationship type
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            # Convert toPascalCaseClass name
            class_name = ''.join(word.capitalize() for word in name.split('_'))
            desc = edge.get("description", f"A {name} relationship.")
            
            code_lines.append(f'class {class_name}(EdgeModel):')
            code_lines.append(f'    """{desc}"""')
            
            attrs = edge.get("attributes", [])
            if attrs:
                for attr in attrs:
                    attr_name = attr["name"]
                    attr_desc = attr.get("description", attr_name)
                    code_lines.append(f'    {attr_name}: EntityText = Field(')
                    code_lines.append(f'        description="{attr_desc}",')
                    code_lines.append(f'        default=None')
                    code_lines.append(f'    )')
            else:
                code_lines.append('    pass')
            
            code_lines.append('')
            code_lines.append('')
        
        # Generate type dictionary
        code_lines.append('# ============== Type configuration ==============')
        code_lines.append('')
        code_lines.append('ENTITY_TYPES = {')
        for entity in ontology.get("entity_types", []):
            name = entity["name"]
            code_lines.append(f'    "{name}": {name},')
        code_lines.append('}')
        code_lines.append('')
        code_lines.append('EDGE_TYPES = {')
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            class_name = ''.join(word.capitalize() for word in name.split('_'))
            code_lines.append(f'    "{name}": {class_name},')
        code_lines.append('}')
        code_lines.append('')
        
        # generating edgessource_targetsmapping
        code_lines.append('EDGE_SOURCE_TARGETS = {')
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            source_targets = edge.get("source_targets", [])
            if source_targets:
                st_list = ', '.join([
                    f'{{"source": "{st.get("source", "Entity")}", "target": "{st.get("target", "Entity")}"}}'
                    for st in source_targets
                ])
                code_lines.append(f'    "{name}": [{st_list}],')
        code_lines.append('}')
        
        return '\n'.join(code_lines)

